name: Deploy to Beanstalk
on:
    push:
      branches:
      - dev

env:
  S3_BUCKET: everesto-dev-shared-artifacts
  ARTIFACT_NAME: fastapi-backend-deploy.zip
  APP_NAME: everesto-${{github.ref}}-backend

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Display Branch Name
          run: |
            echo "Branch: ${{ github.ref }}"

                    
# jobs:
#     build:
#       runs-on: ubuntu-latest
#       steps:
  
#       - name: Checkout source code
#         uses: actions/checkout@v2
  
#       - name: Generate deployment package
#         run: zip -r fastapi-backend-deploy.zip . -x '*.git*'
  
#       - name: Deploy to EB
#         uses: einaregilsson/beanstalk-deploy@v22
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: fastapi-backend
#           environment_name: MyApplication-Environment
#           version_label: 0.0.1
#           region: eu-west-3
#           deployment_package: fastapi-backend-deploy.zip