name: Deploy to Beanstalk
on:
    push:
      branches:
      - dev
      - prod

env:
  S3_BUCKET: everesto-dev-shared-artifacts
  ARTIFACT_NAME: fastapi-backend-deploy.zip
  APP_NAME: everesto-${{github.ref_name}}-backend

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Display Branch Name
          run: |
            echo "Branch: ${{ github.ref_name }}"

        - name: Check directory contents before zipping
          run: ls -la

        - name: Generate deployment package
          run: |
            zip -rv ${{env.APP_NAME}}.zip . -x ".github/*" "venv/*" ".gitignore" "__pycache__/*" ".git/*" "app/__pycache__/*"
        
        - name: Check directory contents after zipping
          run: ls -la

        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v3
          with:
              name: ${{ env.ARTIFACT_NAME }}
              path: ${{env.APP_NAME}}.zip
              retention-days: 3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-3

        - name: Upload to S3
          run: aws s3 cp ${{env.APP_NAME}}.zip s3://${{env.S3_BUCKET}}/backend/${{env.APP_NAME}}.zip
            
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Deploy to Beanstalk
  #     uses: einaregilsson/beanstalk-deploy@v22
  #     with:
  #       aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       application_name: ${{ env.APP_NAME }}
  #       environment_name: MyApplication-Environment
  #       version_label: v-${{ github.sha }}
  #       region: eu-west-3
  #       deployment_package: fastapi-backend-deploy.zip

